export const questions = [
    "Have you ever been doing something and felt like you were born to do that? (If so, what were you doing?)",
    "What has been the worst time in your life?",
    "What is one of the worst things another person has done to you?",
    "What is one of the worst things you have done to another person?",
    "What is something someone said to you that has stuck with you for a long time?",
    "What is one of the best compliments you have received?",
    "What is a guilty pleasure for you?",
    "What is something you are missing?",
    "What is a physical location that is important to you and why?",
    "What is the nicest thing someone has done for you?",
    "What is your biggest insecurity about your body?",
    "What do you think is a good quality about yourself?",
    "What do you think is a quality about yourself that needs work?",
    "What took you a long time to realize?",
    "What is something about me that you don't think you know about myself?",
    "What is one thing you want to accomplish before you die?",
    "What is something you were not allowed to do as a child?",
    "What was your first impression of me?",
    "What was one of the best days of your life?",
    "What do you dread?",
    "What are you looking forward to?",
    "How would you hope to be described at your funeral?",
    "What frustrates you about other people?",
    "What fills you with awe?",
    "What is something you enjoy doing alone?",
    "What is something important about yourself that I don't know about you yet?",
    "What is one thing that you wish people understood about you?",
    "What is keeping you from being happy?",
    "Have you ever been in love?",
    "What is a skill you want?",
    "What piece of media do you go to for comfort? (Song, book, movie, etc.)",
    "What is your proudest accomplishment?",
    "What makes you laugh?",
    "What is one of your hot takes?",
    "What are the two biggest lessons you've learned from previous relationships?",
    "What do you think love is?",
    "What do most people over- or underestimate about you?",
    "What is an event from the past you want to see a recording of?",
    "What do you think about when you're alone?",
    "Do you judge a book by its cover?",
    "Are you confrontational?",
    "What is something you live by?",
    "Which parent are you most like and why?",
    "Who is an important person in your life and why?",
    "Who is a person you look up to and why?"
]